draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_set_font(fnt_menu)
image_xscale = max(1,ceil((string_width_ext(txt,sep,w)+40)/64))
image_yscale = max(1,ceil((string_height_ext(txt,sep,w)+40)/64))
//draw_set_color(#FFFFFF*!(abs(mouse_x-x)<=sprite_width/2 && abs(mouse_y-y)<=sprite_height/2))
draw_sprite_ext(spr_gui,abs(mouse_x-x)<=sprite_width/2 && abs(mouse_y-y)<=sprite_height/2,x,y,image_xscale,1,0,c_white,1)
draw_text(x,y,txt)
draw_set_halign(fa_left)
draw_set_valign(fa_top)
draw_set_font(fnt_default)
//draw_set_color(c_white)